							<div class="block marker">
								<h2 class="line"><i></i>Новинки</h2>
								
								<div class="catalog marker">
									<div class="item">
										<div class="wrap">
											<div class="name">
												<a href="/catalog/2/1/">Беговая дорожка  ALEXA CF 1801Беговая дорожка  ALEXA CF 1801Беговая дорожка  ALEXA CF 1801</a>
											</div>
											<div class="info">
												<div class="photo">
													<img src="http://starfit.ru/files/products/1.jpg" class="image">
												</div>
												<div class="price-container">
													<div class="old-price">123450 р.</div>
													<div class="price">198000 р.</div>
													<a href="/catalog/2/1/"><img src="/image/btn-more.png"></a>
												</div>
												<div class="clearfix"></div>
											</div>
										</div>
									</div>
									
									<div class="item">
										<div class="wrap">
											<div class="name">
												<a href="/catalog/2/1/">Беговая дорожка  ALEXA CF 1801Беговая дорожка  ALEXA CF 1801Беговая дорожка  ALEXA CF 1801</a>
											</div>
											<div class="info">
												<div class="photo">
													<img src="http://starfit.ru/files/products/1.jpg" class="image">
												</div>
												<div class="price-container">
													<div class="old-price">123450 р.</div>
													<div class="price">198000 р.</div>
													<a href="/catalog/2/1/"><img src="/image/btn-more.png"></a>
												</div>
												<div class="clearfix"></div>
											</div>
										</div>
									</div>
									
									<div class="item">
										<div class="wrap">
											<div class="name">
												<a href="/catalog/2/1/">Беговая дорожка  ALEXA CF 1801Беговая дорожка  ALEXA CF 1801Беговая дорожка  ALEXA CF 1801</a>
											</div>
											<div class="info">
												<div class="photo">
													<img src="http://starfit.ru/files/products/1.jpg" class="image">
												</div>
												<div class="price-container">
													<div class="old-price">123450 р.</div>
													<div class="price">198000 р.</div>
													<a href="/catalog/2/1/"><img src="/image/btn-more.png"></a>
												</div>
												<div class="clearfix"></div>
											</div>
										</div>
									</div>
								</div>
							</div>
							
							<div class="block marker">
								<h2 class="line"><i></i>Лидеры продаж</h2>
								
								<div class="catalog marker">
									<div class="item">
										<div class="wrap">
											<div class="name">
												<a href="/catalog/2/1/">Беговая дорожка  ALEXA CF 1801Беговая дорожка  ALEXA CF 1801Беговая дорожка  ALEXA CF 1801</a>
											</div>
											<div class="info">
												<div class="photo">
													<img src="http://starfit.ru/files/products/1.jpg" class="image">
												</div>
												<div class="price-container">
													<div class="old-price">123450 р.</div>
													<div class="price">198000 р.</div>
													<a href="/catalog/2/1/"><img src="/image/btn-more.png"></a>
												</div>
												<div class="clearfix"></div>
											</div>
										</div>
									</div>
									
									<div class="item">
										<div class="wrap">
											<div class="name">
												<a href="/catalog/2/1/">Беговая дорожка  ALEXA CF 1801Беговая дорожка  ALEXA CF 1801Беговая дорожка  ALEXA CF 1801</a>
											</div>
											<div class="info">
												<div class="photo">
													<img src="http://starfit.ru/files/products/1.jpg" class="image">
												</div>
												<div class="price-container">
													<div class="old-price">123450 р.</div>
													<div class="price">198000 р.</div>
													<a href="/catalog/2/1/"><img src="/image/btn-more.png"></a>
												</div>
												<div class="clearfix"></div>
											</div>
										</div>
									</div>
									
									<div class="item">
										<div class="wrap">
											<div class="name">
												<a href="/catalog/2/1/">Беговая дорожка  ALEXA CF 1801Беговая дорожка  ALEXA CF 1801Беговая дорожка  ALEXA CF 1801</a>
											</div>
											<div class="info">
												<div class="photo">
													<img src="http://starfit.ru/files/products/1.jpg" class="image">
												</div>
												<div class="price-container">
													<div class="old-price">123450 р.</div>
													<div class="price">198000 р.</div>
													<a href="/catalog/2/1/"><img src="/image/btn-more.png"></a>
												</div>
												<div class="clearfix"></div>
											</div>
										</div>
									</div>
								</div>
							</div>
							
