							<div class="catalog">
								<ul class="lvl1">
									<li>
										<a href="/catalog/1/">Кардиотренажеры</a>
										<ul class="lvl2">
											<li><a href="/catalog/2/">Беговые дорожки</a></li>
											<li><a href="/catalog/3/">Эллиптические тренажеры и степперы</a></li>
											<li><a href="/catalog/4/">Велотренажеры</a></li>
											<li><a href="/catalog/5/">Гребные</a></li>
										</ul>
									</li>
									<li>
										<a href="/catalog/6/">Силовые тренажеры</a>
										<ul class="lvl2">
											<li><a href="/catalog/7/">Блочные</a></li>
											<li><a href="/catalog/8/">Мультистанции</a></li>
											<li><a href="/catalog/9/">Скамьи и стойки</a></li>
										</ul>
									</li>
									<li>
										<a href="/catalog/10/">Аксессуары</a>
										<ul class="lvl2">
											<li><a href="/catalog/11/">Гантели атлетические</a></li>
											<li><a href="/catalog/12/">Гантели аэробные</a></li>
											<li><a href="/catalog/13/">Грифы и диски</a></li>
											<li><a href="/catalog/14/">Аэробика и фитнес</a></li>
											<li><a href="/catalog/15/">Мячи</a></li>
											<li><a href="/catalog/16/">Стойки и рукоятки</a></li>
										</ul>
									</li>
								</ul>
							</div>
