<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title><?= h( $this -> meta_title ) ?></title>
		<meta name="keywords" content="<?= h( $this -> meta_keywords ) ?>"/> 
		<meta name="description" content="<?= h( $this -> meta_description ) ?>"/> 
		<script type="text/javascript" src="/js/jquery.min.js"></script>
		<script type="text/javascript" src="/js/custom.js"></script>
		<link type="text/css" rel="stylesheet" href="/css/base.css" />
		<link type="text/css" rel="stylesheet" href="/css/style.css" />
	</head>
	<body>
		<div class="animate_wrap"></div>
		<div id="main">
			<div id="wrap">
				<div class="b-header">
					<div class="top">
						<div class="contacts">
<?= $this->contact ?>
						</div>
					</div>
					<a href="/" class="logo"><img src="/image/logo.png" /></a>
					<div class="phones">
<?= $this->phone ?>
					</div>
					<div class="search">
<?= $this->search ?>
					</div>
					<div class="basket">
<?= $this->cart ?>
					</div>
					<div class="login">
<?= $this->subscribe ?>
					</div>
<?= $this->menu ?>
				</div>
				<div class="b-content">
					<div class="left">
						<div class="wrap">
<?= $this->catalogue ?>
<?= $this->article ?>
						</div>
					</div>
					<div class="right">
						<div class="wrap">
<?= $this->teaser ?>
<?= $this->marker ?>
<?= $this->content ?>
						</div>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="b-promo">
<?= $this->advice ?>
					<div class="copyright">
<?= $this->copyright ?>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>
