<!DOCTYPE html>
<html>
	<head>
		<title><?= $this->escape( $this -> meta_title ) ?></title>
		<meta name="keywords" content="<?= $this->escape( $this -> meta_keywords ) ?>"/> 
		<meta name="description" content="<?= $this->escape( $this -> meta_description ) ?>"/> 
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<script type="text/javascript" src="/js/jquery.min.js"></script>
		<script type="text/javascript" src="/js/custom.js"></script>
		<link type="text/css" rel="stylesheet" href="/css/base.css" />
		<link type="text/css" rel="stylesheet" href="/css/style.css" />
	</head>
	<body>
		<div class="animate_wrap"></div>
		<div id="teaser">
<?= $this->teaser ?>
		</div>
		<div id="main">
			<div id="wrap">
				<div class="b-header">
					<div class="top">
						<div class="contacts">
<?= $this->contact ?>
						</div>
					</div>
					<a href="/" class="logo"><img src="/image/logo.png" /></a>
					<div class="phones">
<?= $this->phone ?>
					</div>
					<div class="search">
<?= $this->search ?>
					</div>
					<div class="basket">
<?= $this->cart ?>
					</div>
					<div class="login">
<?= $this->subscribe ?>
					</div>
<?= $this->menu ?>
				</div>
				<div class="b-content">
					<div class="left">
						<div class="wrap">
<?= $this->catalogue ?>
<?= $this->article ?>
						</div>
					</div>
					<div class="right">
						<div class="wrap">
<?= $this->marker ?>
<?= $this->content ?>
						</div>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="b-promo">
<?= $this->advice ?>
					<div class="copyright">
<?= $this->copyright ?>
					</div>
				</div>
			</div>
		</div>
		<!-- Yandex.Metrika counter -->
		<script type="text/javascript">
		(function (d, w, c) {
			(w[c] = w[c] || []).push(function() {
				try {
					w.yaCounter22454518 = new Ya.Metrika({id:22454518,
							webvisor:true,
							clickmap:true,
							trackLinks:true,
							accurateTrackBounce:true});
				} catch(e) { }
			});

			var n = d.getElementsByTagName("script")[0],
				s = d.createElement("script"),
				f = function () { n.parentNode.insertBefore(s, n); };
			s.type = "text/javascript";
			s.async = true;
			s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

			if (w.opera == "[object Opera]") {
				d.addEventListener("DOMContentLoaded", f, false);
			} else { f(); }
		})(document, window, "yandex_metrika_callbacks");
		</script>
		<noscript><div><img src="//mc.yandex.ru/watch/22454518" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
		<!-- /Yandex.Metrika counter -->
		<div id="LI_counter" style="display:none; " >
			<!--LiveInternet counter--><script type="text/javascript"><!--
			document.write("<a href='http://www.liveinternet.ru/click' "+
			"target=_blank><img src='//counter.yadro.ru/hit?t45.15;r"+
			escape(document.referrer)+((typeof(screen)=="undefined")?"":
			";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
			screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
			";"+Math.random()+
			"' alt='' title='LiveInternet' "+
			"border='0' width='31' height='31'><\/a>")
			//--></script><!--/LiveInternet-->
		</div>
	</body>
</html>
