							<div class="block first">
								<h1><i></i>Статьи</h1>
								<div class="b-articles">
<? foreach ($this->article_list as $article_item) { ?>
									<div class="item first ">
										<div class="">
											<div class="name">
												<a href="<?= url_for(array('controller' => 'article', 'action' => 'item', 'id' => $article_item->get_id())) ?>"><?= $article_item->get_article_title() ?></a>
											</div>
										</div>
										<div class="clearfix"></div>
									</div>
<? } ?>
									<div class="clearfix"></div>
								</div>
							</div>

