							<div class="block articles">
								<h2><i></i>Статьи</h2>
<? foreach ($this->article_list as $article_item) { ?>
								<div class="item">
									<div class="name"><a href="<?= $article_item->get_article_url() ?>"><?= $article_item->get_article_title() ?></a></div>
								</div>
<? } ?>
								<div class="more"><a href="<?= url_for(array('controller' => 'article')) ?>">Все статьи</a></div>
							</div>

