							<div class="block articles">
								<h2><i></i>Статьи</h2>
								<div class="item">
									<div class="name"><a href="/articles/5/">Спортивные тренажеры Alex</a></div>
								</div>
								<div class="item">
									<div class="name"><a href="/articles/4/">Тренажеры WNQ</a></div>
								</div>
								<div class="item">
									<div class="name"><a href="/articles/3/">О тренажерах WNQ Magnum</a></div>
								</div>
								<div class="more"><a href="/articles/">Все статьи</a></div>
							</div>

