							<link rel="stylesheet" type="text/css" href="/js/highslide/highslide.css" />
							<script type="text/javascript" src="/js/highslide/highslide-with-gallery.js"></script>
							<script type="text/javascript">
								hs.graphicsDir = '/js/highslide/graphics/';
								hs.transitions = ['expand', 'crossfade'];
								hs.outlineType = 'rounded-white';
								hs.fadeInOut = true;
								hs.align = 'center';
								hs.dimmingOpacity = 0.85;
								
								// Add the controlbar
								hs.addSlideshow({
									interval: 5000,
									repeat: false,
									useControls: true,
									fixedControls: 'fit',
									overlayOptions: {
										opacity: .75,
										position: 'bottom center',
										hideOnMouseOut: true
									} 
								});
							</script>
							<div class="block first">
								<h1><i></i><?= $this->get_product_title() ?></h1>
								<div class="b-catalog-item">
									<div class="info">
										<div class="photo">
<? 		$marker_list = $this->get_marker_list(); ?>
<? 		if ($marker_list) { ?>
											<div class="marker">
<? 			foreach ($marker_list as $marker) { ?>
												<img src="<?= $marker->get_marker_picture() ?>"><br/>
<? 			} ?>
											</div>
<? 		} ?>
											<a href="<?= $this->get_product_image() ?>" class="highslide " onclick="return hs.expand(this)">
												<img src="<?= $this->get_product_image() ?>" class="image" />
											</a>
										</div>
										<div class="price-container">
											<div class="old-price">
<? if ($this->get_product_price_old()) { ?>
												<?= $this->get_product_price_old() ?> р.
<? } ?>
											</div>
											<div class="price">
												<?= $this->get_product_price() ?> р.
											</div>
											<a href="#" onclick="buyItem(<?= $this->get_id() ?>);return false;"><img src="/image/btn-buy.png" /></a>
											<div class="in-basket">
												Товар отправлен в корзину.
												<br/>
												<a href="<?= url_for(array('controller' => 'order')) ?>">Оформить заказ?</a>
											</div>
										</div>
										<div class="clearfix"></div>
									</div>
									<div class="text">
<?= $this->get_product_description() ?>
<? if ($this->get_product_instruction()) { ?>
										<p>&raquo; <a href="<?= $this->get_product_instruction() ?>">Инструкция</a></p>
<? } ?>
									</div>
									<div>
										<a href="<?= $this->get_catalogue()->get_catalogue_url() ?>">Вернуться в раздел "<?= $this->get_catalogue()->get_catalogue_title() ?>"</a>
									</div>
								</div>
							</div>
