							<link rel="stylesheet" type="text/css" href="/js/highslide/highslide.css" />
							<script type="text/javascript" src="/js/highslide/highslide-with-gallery.js"></script>
							<script type="text/javascript">
								hs.graphicsDir = '/js/highslide/graphics/';
								hs.transitions = ['expand', 'crossfade'];
								hs.outlineType = 'rounded-white';
								hs.fadeInOut = true;
								hs.align = 'center';
								hs.dimmingOpacity = 0.85;
								
								// Add the controlbar
								hs.addSlideshow({
									interval: 5000,
									repeat: false,
									useControls: true,
									fixedControls: 'fit',
									overlayOptions: {
										opacity: .75,
										position: 'bottom center',
										hideOnMouseOut: true
									} 
								});
								
								function setMark(mark) {
									$('.vote .star').removeClass('active');
									$('.vote .star:lt(' + mark + ')').addClass('active');
								}
								
								$(function(){
									$('.vote .star').mouseenter(function(){
										setMark($(this).attr('mark'));
									}).click(function(){
										$.post('/product/vote/<?= $this->get_id() ?>', {action: 'vote', mark: $(this).attr('mark')}, function(data){
											var rating = Math.round(data.rating);
											$('.vote').attr('rating', rating); $('.vote').mouseleave();
										}, 'json');
									});
									$('.vote').mouseleave(function(){
										setMark($(this).attr('rating'));
									});
								});
							</script>
							<div class="block first">
								<h1><i></i><?= $this->get_product_title() ?></h1>
								<div class="b-catalog-item">
									<div class="info">
										<div class="photo">
<? 		$marker_list = $this->get_marker_list(); ?>
<? 		if ($marker_list) { ?>
											<div class="marker">
<? 			foreach ($marker_list as $marker) { ?>
												<img src="<?= $marker->get_marker_picture() ?>"><br/>
<? 			} ?>
											</div>
<? 		} ?>
											<a href="<?= $this->get_product_image() ?>" class="highslide" onclick="return hs.expand(this)">
												<img src="<?= $this->get_product_image() ?>" class="image" />
											</a>
										</div>
										<div class="price-container">
<? if ($this->get_product_price_old()) { ?>
											<div class="old-price">
												<?= $this->get_product_price_old() ?> руб.
											</div>
<? } ?>
											<div class="price">
<? if ($this->get_product_price()) { ?>
												<?= $this->get_product_price() ?> руб.
<? } else { ?>
												<span style="font-size: 20px;">цену уточняйте</span>
<? } ?>
											</div>
<? if ($brand = $this->get_brand()) { ?>
											<div class="brand">
												Производитель:<br/>
												<img src="<?= $brand->get_brand_image() ?>" />
											</div>
<? } ?>
<? $rating = round($this->get_product_rating()); ?>
											<div class="vote" rating="<?= $rating ?>">
<? for ($i = 1; $i <= 5; $i++) { ?>
												<div class="star<? if ($rating >= $i) { ?> active<? } ?>" mark="<?= $i ?>"></div>
<? } ?>
											</div>
<? if ($this->get_product_stock()) { ?>
											<div class="stock">
												Есть в наличии
											</div>
<? } ?>
											<div class="share">
												<script type="text/javascript">(function() {
												  if (window.pluso)if (typeof window.pluso.start == "function") return;
												  if (window.ifpluso==undefined) { window.ifpluso = 1;
													var d = document, s = d.createElement('script'), g = 'getElementsByTagName';
													s.type = 'text/javascript'; s.charset='UTF-8'; s.async = true;
													s.src = ('https:' == window.location.protocol ? 'https' : 'http')  + '://share.pluso.ru/pluso-like.js';
													var h=d[g]('body')[0];
													h.appendChild(s);
												  }})();</script>
												<div class="pluso" data-background="transparent" data-options="small,square,line,horizontal,counter,theme=04" data-services="vkontakte,odnoklassniki,facebook,twitter,moimir,livejournal"></div>
											</div>
											<div class="button">
												<a href="#" onclick="buyItem(<?= $this->get_id() ?>);return false;"><img src="/image/btn-buy.png" /></a>
												<div class="in-basket">
													Товар отправлен в корзину.
													<br/>
													<a href="<?= url_for(array('controller' => 'order')) ?>">Оформить заказ?</a>
												</div>
											</div>
										</div>
<? if ($picture_list = $this->get_picture_list()) { ?>
										<div class="picture-container">
											<div class="wholesale">
												<a href="/subscribe"><img src="/image/wholesale-button.png" ></a>
											</div>
<? 		foreach ($picture_list as $picture) { ?>
											<a href="<?= $picture->get_picture_image() ?>" class="highslide" onclick="return hs.expand(this)">
												<img src="<?= $picture->get_picture_image() ?>/c/85/85" />
											</a>
<? 		} ?>
										</div>
<? } else { ?>
										<div class="picture-container empty">
											<div class="wholesale">
												<a href="/subscribe"><img src="/image/wholesale-button.png" ></a>
											</div>
										</div>
<? } ?>
										<div class="clearfix"></div>
									</div>
								</div>
								<div class="description">
									<div class="title">
										Описание
									</div>
<?= $this->get_product_description() ?>

<? if ($property_list = $this->get_property_list()) { ?>
									<table class="property_table">
<? 		foreach ($property_list as $property) { ?>
										<tr>
											<td class="name">
												<?= $property->get_property_title() ?>
											</td>
											<td class="value">
<? if ($property->get_property_kind() == 'boolean') { ?>
												<?= $property->get_property_value() ? 'есть' : 'нет' ?>
<? } else { ?>
												<?= $property->get_property_value() ?><?= $property->get_property_unit() ? ' ' . $property->get_property_unit() : '' ?>
<? } ?>
											</td>
										</tr>
<? 		} ?>
									</table>
<? } ?>
<? if ($this->get_product_instruction()) { ?>
									<p>&raquo; <a href="<?= $this->get_product_instruction() ?>">Инструкция</a></p>
<? } ?>
								</div>
<? if ($this->get_product_video()) { ?>
								<div class="description">
									<div class="title">
										Видео
									</div>
									<div style="text-align: center">
<?= $this->get_product_video() ?>
									</div>
								</div>
<? } ?>
<? if ($product_link_list = $this->get_product_link_list()) { ?>
								<div class="description">
									<div class="title">
										C этим товаром покупают
									</div>
									<div class="catalog">
<? 		foreach ($product_link_list as $product_item) { ?>
										<div class="item">
											<div class="wrap">
												<div class="name">
													<a href="<?= $product_item->get_product_url() ?>"><?= $product_item->get_product_title() ?></a>
												</div>
												<div class="info">
													<div class="photo">
<? 			$marker_list = $product_item->get_marker_list(); ?>
<? 			if ($marker_list) { ?>
														<div class="marker">
<? 				foreach ($marker_list as $marker) { ?>
															<img src="<?= $marker->get_marker_picture() ?>"><br/>
<? 				} ?>
														</div>
<? 			} ?>
														<a href="<?= $product_item->get_product_url() ?>">
															<img src="<?= $product_item->get_product_image() ?>" class="image">
														</a>
													</div>
													<div class="price-container">
														<div class="old-price">
<? 			if ($product_item->get_product_price_old()) { ?>
															<?= $product_item->get_product_price_old() ?> р.
<? 			} ?>
														</div>
														<div class="price">
															<?= $product_item->get_product_price() ?> р.
														</div>
														<a href="<?= $product_item->get_product_url() ?>"><img src="/image/btn-more.png"></a>
													</div>
													<div class="clearfix"></div>
												</div>
											</div>
										</div>
<? 		} ?>
									</div>
								</div>
<? } ?>
								<div>
									<a href="<?= $this->get_catalogue()->get_catalogue_url() ?>">Вернуться в раздел "<?= $this->get_catalogue()->get_catalogue_title() ?>"</a>
								</div>
								<div class="clearfix"></div>
							</div>
							<div class="clearfix"></div>
