							<div class="block first">
								<h1 class="line h1"><i></i><? 
								if($this->catalogue->get_catalogue_short_title()){
									echo $this->catalogue->get_catalogue_short_title(); 
								}else{
									echo $this->catalogue->get_catalogue_title();
								}
								?></h1>
<? if ($this->filter_list) { ?>
								<div class="filter">
									Показать только:
<? 		foreach ($this->filter_list as $filter_item) { ?>
									<a href="<?= $filter_item->get_filter_url() ?>"<? if ($this->filter && $filter_item->get_id() == $this->filter->get_id()) { ?> class="selected"<? } ?>><?= $filter_item->get_filter_title() ?></a>
<? 		} ?>
								</div>
<? } ?>
								
								<div class="catalog">
<? foreach ($this->product_list as $product_item) { ?>
									<div class="item">
										<div class="wrap">
											<div class="name">
												<a href="<?= $product_item->get_product_url() ?>"><?= $product_item->get_product_title() ?></a>
											</div>
											<div class="info">
												<div class="photo">
<? 		$marker_list = $product_item->get_marker_list(); ?>
<? 		if ($marker_list) { ?>
													<div class="marker">
<? 			foreach ($marker_list as $marker) { ?>
														<img src="<?= $marker->get_marker_picture() ?>"><br/>
<? 			} ?>
													</div>
<? 		} ?>
													<img src="<?= $product_item->get_product_image() ?>" class="image">
												</div>
												<div class="price-container">
													<div class="old-price">
<? 		if ($product_item->get_product_price_old()) { ?>
														<?= $product_item->get_product_price_old() ?> р.
<? 		} ?>
													</div>
													<div class="price">
														<?= $product_item->get_product_price() ?> р.
													</div>
													<a href="<?= $product_item->get_product_url() ?>"><img src="/image/btn-more.png"></a>
												</div>
												<div class="clearfix"></div>
											</div>
										</div>
									</div>
<? } ?>
								</div>
<? if ($this->filter && $this->filter->get_filter_description()) { ?>
<?= $this->filter->get_filter_description() ?>
<? } elseif ($this->catalogue->get_catalogue_description()) { ?>
<?= $this->catalogue->get_catalogue_description() ?>
<? } ?>
							</div>
