							<div class="block first">
								<h1><i></i>Оформление заказа</h1>
<? if ($this->get_quantity()) { ?>
								<div class="b-order">
									<table class="items">
										<tr>
											<td width="50">
												&nbsp;
											</td>
											<td class="ac">
												<b>Товар</b>
											</td>
											<td width="50" class="ac">
												<b>Цена</b>
											</td>
											<td width="50" class="ac">
												<b>Кол-во</b>
											</td>
											<td width="50" class="ac">
												<b>Стоимость</b>
											</td>
										</tr>
<? 		foreach ($this->get() as $item) { ?>
<? 			$product_item = model::factory('product')->get($item->id); ?>
										<tr>
											<td width="50">
												<img src="<?= $product_item->get_product_image() ?>" class="image" />
											</td>
											<td>
												<?= $product_item->get_product_title() ?>
											</td>
											<td width="50" class="ar">
												<?= $product_item->get_product_price() ?>
											</td>
											<td width="50" class="ar">
												<?= $item->quantity ?>
											</td>
											<td width="50" class="ar">
												<?= $item->quantity * $product_item->get_product_price() ?>
											</td>
										</tr>
<? 		} ?>
										<tr>
											<td colspan="3" class="ar">
												<strong>Итого:</strong>
											</td>
											<td width="50" class="ar">
												<strong><?= $this->get_quantity() ?></strong>
											</td>
											<td width="50" class="ar">
												<strong><?= $this->get_sum() ?>
											</td>
										</tr>
									</table>
									<div class="form">
										<form id="sendmessage" method="post">
											<div class="field">
												Ваше имя <span class="require">*</span>:
												<br />
												<input type="text" value="<?= h($this->from_request('name')) ?>" name="name" class="order input require" />
<? if ($this->error['name']) { ?>
									<span class="require"><?= $this->error['name'] ?></span>
<? } ?>
											</div>
											<div class="field">
												Ваш телефон <span class="require">*</span>:
												<br />
												<input type="text" value="<?= h($this->from_request('phone')) ?>" name="phone" class="order input require" />
<? if ($this->error['phone']) { ?>
									<span class="require"><?= $this->error['phone'] ?></span>
<? } ?>
											</div>
											<div class="field">
												Ваш e-mail <span class="require">*</span>:
												<br />
												<input type="text" value="<?= h($this->from_request('email')) ?>" name="email" class="order input require" />
<? if ($this->error['email']) { ?>
									<span class="require"><?= $this->error['email'] ?></span>
<? } ?>
											</div>
											<div class="field">
												Адрес доставки:
												<br />
												<textarea name="address" class="order input"><?= h($this->from_request('address')) ?></textarea>
											</div>
											<div class="field">
												Комментарий:
												<br />
												<textarea name="comment" class="order input"><?= h($this->from_request('comment')) ?></textarea>
											</div>
											<div class="field">
												<input type="image" src="/image/btn-order.png" />
											</div>
										</form>
									</div>
								</div>
<? } elseif (session::flash('success')) { ?>
								<p style="color: #448600; font-size: 16px;"><b>Спасибо. Ваш заказ отправлен.</b></p>
<? } else { ?>
								<p style="font-size: 16px;"><b>Ваша корзина пуста.</b></p>
<? } ?>
							</div>
