В интернет-магазин StarFit поступил новый заказ.<br/><br/>
<? $item_index = 1; ?>
<? foreach ($this->get() as $item) { ?>
<? 		$product_item = model::factory('product')->get($item->id); ?>
<?= $item_index ?>. <?= $product_item->get_product_title() ?> - <?= $item->quantity ?> x <?= $item->price ?> (<?= $item->price ?> р.)<br/>
<? 		$item_index++; ?>
<? } ?>
<br/>
Общая стоимость заказа: <?= $this->get_sum() ?> р.<br/><br/>

ФИО: <?= $this->from_request('name') ?><br/>
Телефон: <?= $this->from_request('phone') ?><br/>
Email: <?= $this->from_request('email') ?><br/>
Адрес: <?= $this->from_request('address') ?><br/>
Комментарий: <?= $this->from_request('comment') ?><br/>
