					<div class="block first">
						<div class="b-form">
							<h1><i></i>Заказать обратный звонок</h1>
<? if (session::flash('success')) { ?>
							<p style="color: #448600; font-size: 16px;"><b>Спасибо за Вашу заявку. Наш менеджер перезвонит Вам в указанное время.</b></p>
<? } else { ?>
							<form method="POST" id="callback-form">
								<div class="field">
									Ваше имя, фамилия, отчество <span class="require">*</span>:
									<br />
									<input type="text" class="input" name="callback_person" value="<?= $this->escape($this->from_request('callback_person')) ?>" />
<? if ($this->error['callback_person']) { ?>
									<span class="require"><?= $this->error['callback_person'] ?></span>
<? } ?>
								</div>
								<div class="field">
									Ваш телефон <span class="require">*</span>:
									<br />
									<input type="text" class="input" name="callback_phone" value="<?= $this->escape($this->from_request('callback_phone')) ?>" />
<? if ($this->error['callback_phone']) { ?>
									<span class="require"><?= $this->error['callback_phone'] ?></span>
<? } ?>
								</div>
								<div class="field">
									Удобное время звонка:
									<br />
									<input type="text" class="input" name="callback_time" value="<?= $this->escape($this->from_request('callback_time')) ?>" />
<? if ($this->error['callback_time']) { ?>
									<span class="require"><?= $this->error['callback_time'] ?></span>
<? } ?>
								</div>
								<div class="field">
									Комментарий<br>(например, интересующий товар):
									<br />
									<textarea class="input" name="callback_comment"><?= $this->escape($this->from_request('callback_comment')) ?></textarea>
<? if ($this->error['callback_comment']) { ?>
									<span class="require"><?= $this->error['callback_comment'] ?></span>
<? } ?>
								</div>
								<div class="field">
                                    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
                                    <script>
                                        function onSubmit(token) {
                                            document.getElementById("callback-form").submit();
                                        }
                                    </script>
									<input type="button" value="Заказать звонок" class="g-recaptcha" data-sitekey="<?= get_preference('recaptcha_public') ?>" data-callback='onSubmit' />
<? if ($this->error['captcha']) { ?>
                                    <span class="require"><?= $this->error['captcha'] ?></span>
<? } ?>
								</div>
							</form>
<? } ?>
						</div>
					</div>
