					<div class="block first">
						<div class="b-form">
							<h1><i></i>Станьте нашим оптовым покупателем!</h1>
<? if (session::flash('success')) { ?>
							<p style="color: #448600; font-size: 16px;"><b>Спасибо. Ваша анкета отправлена.</b></p>
<? } ?>
							<p>Если Вы хотите работать с нашей компнией на постоянной основе, заполните анкету на данной странице. В ответ наш менеджер вышлет Вам информацию об условиях сотрудничества и актуальный прайс-лист. Рассылка прайс-листа осуществляется не чаще 1 раза в месяц.</p>
							<form method="POST">
								<div class="field">
									E-mail <span class="require">*</span>:
									<br />
									<input type="text" class="input" name="email" value="<?= $this->escape($this->from_request('email')) ?>" />
<? if ($this->error['email']) { ?>
									<span class="require"><?= $this->error['email'] ?></span>
<? } ?>
								</div>
								<div class="field">
									Ваше имя, фамилия, отчество <span class="require">*</span>:
									<br />
									<input type="text" class="input" name="person" value="<?= $this->escape($this->from_request('person')) ?>" />
<? if ($this->error['person']) { ?>
									<span class="require"><?= $this->error['person'] ?></span>
<? } ?>
								</div>
								<div class="field">
									Название компании (для юрлиц):
									<br />
									<input type="text" class="input" name="name" value="<?= $this->escape($this->from_request('name')) ?>" />
<? if ($this->error['name']) { ?>
									<span class="require"><?= $this->error['name'] ?></span>
<? } ?>
								</div>
								<div class="field">
									Тип компании (для юрлиц обязательно):
									<br />
									<select name="type" style="width: 318px;">
										<option value=""></option>
<? foreach ($this->type_list as $value => $title) { ?>
										<option value="<?= $value ?>"<? if ($this->in_request('type', $value)) { ?> selected="selected"<? } ?>><?= $title ?></option>
<? } ?>
									</select>
<? if ($this->error['type']) { ?>
									<span class="require"><?= $this->error['type'] ?></span>
<? } ?>
								</div>
								<div class="field">
									Телефон (для юрлиц обязательно):
									<br />
									<input type="text" class="input" name="phone" value="<?= $this->escape($this->from_request('phone')) ?>" />
<? if ($this->error['phone']) { ?>
									<span class="require"><?= $this->error['phone'] ?></span>
<? } ?>
								</div>
								<div class="field">
									Факс (для юрлиц обязательно):
									<br />
									<input type="text" class="input" name="fax" value="<?= $this->escape($this->from_request('fax')) ?>" />
<? if ($this->error['fax']) { ?>
									<span class="require"><?= $this->error['fax'] ?></span>
<? } ?>
								</div>
								<div class="field fail">
									<img src="/image/captcha.php" style="width: 200px; height: 50px" />
									<input type="text" class="input" name="captcha" value="" style="width: 90px" />
<? if ($this->error['captcha']) { ?>
									<span class="require"><?= $this->error['captcha'] ?></span>
<? } ?>
									<br />
									Введите символы с картинки
								</div>
								<div class="field">
									<input type="submit" value="Зарегистрироваться" class="btn" />
								</div>
							</form>
						</div>
					</div>
