Email: <?= $this->escape($this->from_request('email')) ?><br/>
ФИО: <?= $this->escape($this->from_request('person')) ?><br/>
Название компании: <?= $this->escape($this->from_request('name')) ?><br/>
Тип компании: <?= $this->type_list[$this->escape($this->from_request('type'))] ?><br/>
Телефон: <?= $this->escape($this->from_request('phone')) ?><br/>
Факс: <?= $this->escape($this->from_request('fax')) ?><br/>
